/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws Exception {

        linter(args[0]);
    }

    public static String linter(String filePath) throws Exception {
        Scanner jsScanner;
        String message = "";
        try {
            jsScanner = new Scanner(new File(filePath));
        } catch (FileNotFoundException exception){
            exception.printStackTrace();
            throw new Exception("That file does not exist");
        }
        int counter = 0;
        String newLine = System.getProperty("line.separator");
        while (jsScanner.hasNextLine()){
            counter ++;
            String currentLine = jsScanner.nextLine();
            if (!singleLnValidation(currentLine)) {
                if (message == "") message = message.concat("Line " + counter + " : Missing semicolon.");
                else message = message.concat( newLine + "Line " + counter + " : Missing semicolon.");
            }
        }

        if (message == "") message = "No error found";
        return message;
    }

    public static boolean singleLnValidation (String singleLine) {
        if(
                singleLine.isEmpty() ||
                singleLine.endsWith("}") ||
                singleLine.endsWith("{") ||
                singleLine.endsWith(";") ||
                singleLine.contains("if") ||
                singleLine.contains("else")
        ) return true;
        return false;
    }
}
