/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {


    @Test public void testRestaurantInitExceptionCatcher () throws Exception {
        Throwable exception1 = assertThrows(Exception.class, () -> new Restaurant("test",5));
        assertEquals("Price category need to between 1 to 4 $s", exception1.getMessage());

        Throwable exception2 = assertThrows(Exception.class, () -> new Restaurant(null, 4));
        assertEquals("Restaurant name and price category is needed when launching new business", exception2.getMessage());
    }

    @Test public void testRestaurantConstructor () throws Exception{
        Restaurant test = new Restaurant("test",4);
        String expected = "Welcome to test restaurant, we current have 0.0 stars reviews, and price category is $$$$.";
        String actual = test.toString();
        assertEquals("New restaurant should output a string desc", expected, actual);
    }

    @Test public void testRestaurantAddReview () throws Exception{
        Restaurant test = new Restaurant("test",4);
        test.addReview(new Review("review1", "author1", 5));
        assertTrue("should be able to find author1's review", test.reviews.containsKey("author1"));
        String actual = test.reviews.get("author1").body;
        String expected = "review1";
        assertEquals("Review should be able to added review body in reviews collection", expected, actual);

        assertEquals("stars should be updated", 5.0, test.stars, 0.1);

        test.addReview(new Review("review2","author2", 1));
        test.addReview(new Review("review3","author3", 2));
        assertEquals("stars should be updated", 2.7, test.stars, 0.1);

    }
}
