/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class ShopTest {


    @Test public void testShopInitExceptionCatcher () throws Exception {
        Throwable exception1 = assertThrows(Exception.class, () -> new Shop("test","a good shop", 5));
        assertEquals("Price category need to between 1 to 4 $s", exception1.getMessage());

        Throwable exception2 = assertThrows(Exception.class, () -> new Shop(null, "a bad shop", 4 ));
        assertEquals("Shop name, description and price category are needed when launching new business.",
                exception2.getMessage());
    }

    @Test public void testShopConstructor () throws Exception{
        Shop test = new Shop("test","a good shop",4);
        String expected = "Welcome to test, a good shop, we current have 0.0 stars reviews, and price category is $$$$.";
        String actual = test.toString();
        assertEquals("New Shop should output a string desc", expected, actual);
    }

    @Test public void testShopAddReview () throws Exception{
        Shop test = new Shop("test","a good shop",4);
        test.addReview(new Review("review1", "author1", 5));
        assertTrue("should be able to find author1's review", test.reviews.containsKey("author1"));

        String actual = test.reviews.get("author1").body;
        String expected = "review1";
        assertEquals("Review should be able to added review body in reviews collection", expected, actual);

        assertEquals("stars should be updated", 5.0, test.stars, 0.1);

        test.addReview(new Review("review2","author2", 1));
        test.addReview(new Review("review3","author3", 2));
        assertEquals("stars should be updated", 2.7, test.stars, 0.1);

    }
}
