/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class TheaterTest {


    @Test public void testTheaterInitExceptionCatcher () throws Exception {

        Throwable exception = assertThrows(Exception.class, () -> new Theater(null));
        assertEquals("Theater name is needed when launching new business.",
                exception.getMessage());
    }

    @Test public void testTheaterConstructor () throws Exception{
        Theater test = new Theater("test");
        String expected = "Welcome to test movie theater, we current have no movies yet.";
        String actual = test.toString();
        assertEquals("New Theater should output a string with no movie", expected, actual);
    }

    @Test public void testTheaterAddTheaterReview () throws Exception{
        Shop test = new Shop("test","a good shop",4);
        test.addReview(new Review("review1", "author1", 5));
        assertTrue("should be able to find author1's review", test.reviews.containsKey("author1"));

        String actual = test.reviews.get("author1").body;
        String expected = "review1";
        assertEquals("Review should be able to added review body in reviews collection", expected, actual);

        assertEquals("stars should be updated", 5.0, test.stars, 0.1);

        test.addReview(new Review("review2","author2", 1));
        test.addReview(new Review("review3","author3", 2));
        assertEquals("stars should be updated", 2.7, test.stars, 0.1);

    }
}
