/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinterManyFreakingErrors() throws Exception {
        int expectedErrors = 46;
        String result = App.linter("src/resources/gate.js");
        int actualErrors = result.split("[\n|\r]").length;
        assertEquals("should catch 46 error", expectedErrors, actualErrors);
    }

    @Test public void testLinterOneError() throws Exception {
        String expectedError = "Line 5 : Missing semicolon.";
        String result = App.linter("src/resources/oneError.js");
        assertEquals("should catch 1 error", expectedError, result);
    }

    @Test public void testLinterFewError() throws Exception {
        int expectedErrors = 7;
        String result = App.linter("src/resources/fewErrors.js");
        int actualErrors = result.split("[\n|\r]").length;
        assertEquals("should catch 46 error", expectedErrors, actualErrors);
    }

    @Test public void testLinterNoError() throws Exception {
        String expectedError = "No error found.";
        String result = App.linter("src/resources/noError.js");
        assertEquals("should catch 1 error", expectedError, result);
    }
}
